robustness for script a little more

diff --git a/dae/op_start b/dae/op_start
--- a/dae/op_start
+++ b/dae/op_start
@@ -50,6 +50,10 @@ extract_int()
 {
 	local val=`echo $1 | sed 's,--ctr\([0-9]*\)[-A-Za-z]*,\1,'`
 
+	if test -z "$val"; then 
+		echo "invalid option \"$1\"" >&2
+		exit 1
+	fi
 	if (($val >= $OP_MAX_COUNTERS || $val < 0)); then
 		echo "invalid argument $1: bad counter number" >&2
 		exit 1
